name: "Build & Lint"

on:
  pull_request:
  push:

jobs:
  nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - name: Build
        run: nix-build
      - name: Lint
        run: ./lint.sh
